### ISSUE TITLE
New Release with PHP deprecation fix

### ISSUE THREAD

**Issue by 73nici** [mireo91/RepeatableFields#25] opened 2024-04-11 18:00 UTC
Hi :),

thanks for this awesome package.

Is there currently a new release planned with the deprecation fix for PHP 8.3 https://github.com/mireo91/RepeatableFields/commit/300c19f6b35f7be31540baa949ee4312b62ef020 ?
It would be great if there is new official version without the deprecation warning, because this is currently the only "issue" holding me back from upgrading to PHP 8.3 :).

**Comment by mireo91** [comment] 2024-04-15 11:11
@73nici Hi,
new release will be just small deprecation fix - the one you pointed ( I just marged this one). I will test it on my own before this weenend and after that should be new release. I will be in touch

**Comment by jonnitto** [comment] 2024-04-21 07:25
It would be great if you could release more. We have some projects that need this package and it's annoying if the bug is already fixed but simply not released. According to the credo: Release early, release often

**Comment by mireo91** [comment] 2024-04-22 04:53
the problem is just that I am currently very busy - because I am renovating house. Release v2.2.1 was just created

**Closed by mireo91** 2024-04-22 04:53 UTC
